# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BuzzyMail' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BuzzyMail
  pod 'p2.OAuth2'
  pod 'SwiftyJSON'
  pod 'SwiftVideoBackground', '~> 2.0.0'
  pod 'SideMenu'

  target 'BuzzyMailTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
